---

- hosts: all
  # remote_user: root
  become: yes
  tags: slurm
  roles:
    - name: slurm
      slurm_type_of_node: 'front'

- hosts: all
  # remote_user: root
  become: yes
  tags: slurm
  roles:
    - name: slurm
      slurm_type_of_node: 'wn'
