---

- hosts: all
  become: yes
  roles:
    - name: vm_config

- hosts: slurmserver
  become: yes
  tags: slurm
  roles:
    - name: slurm
      slurm_type_of_node: 'front'
      slurm_wn_nodenames: ['slurmbatch1', 'slurmbatch2']

- hosts: slurmworker
  become: yes
  tags: slurm
  roles:
    - name: slurm
      slurm_type_of_node: 'wn'
      slurm_wn_nodenames: ['slurmbatch1', 'slurmbatch2']
