---

- hosts: all
  become: yes
  roles:
    - name: vm_config

- hosts: all
  become: yes
  tags: slurm
  roles:
    - name: slurm
      slurm_type_of_node: 'front'

- hosts: all
  become: yes
  tags: slurm
  roles:
    - name: slurm
      slurm_type_of_node: 'wn'
