---

  - name: synchronise the munge.key from master node to the worker node (rsync push)
    synchronize:
      src: "/etc/munge/munge.key"
      dest: "/etc/munge/munge.key"
    delegate_to: "{{ slurm_server_name }}"

  - name: Restart Munge service
    service: name=munge state=restarted
    when: not munge_key.stat.exists

  - name: Make sure the munge service is started
    service: name=munge state=started
